modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MPL-2.0"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="logo.png"
authors="${mod_author}"
displayTest="IGNORE_SERVER_VERSION"
description='''
A fork of Tslat's SmartBrainLib powering Metropolize Companions.
'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
